name: Deploy

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        run: npm run build

      - name: Verify build output
        run: ls -la dist

      - name: Deploy
        run: |
          npm install -g gh-pages
          gh-pages -d dist
